### ISSUE TITLE
Special chars in attribute names break feed settings

### ISSUE THREAD

**Issue by bissie** [FACT-Finder-Web-Components/oxid-eshop-module#93] opened 2022-01-11 13:24 UTC
Customer had an attribute with Title _Shopattribute "New"_ 
When open module setting page section _feed settings_, adding a new attribute is not possible and stored attributes are not displayed.
Quotation marks in titles destroy json structure.
Steps to reproduce:
* Create an attribute with Quotation marks in Title
* Open settings page for oxid module

**Comment by a-laurowski** [comment] 2022-01-12 11:14
Hi @bissie and thanks for reporting.
This is going to be fixed in next release

**Comment by m-schiewi** [comment] 2022-02-10 09:09
Issue not fixed in 4.1.0

steps to  reproduce: 
- create an attribute in shop titled "Webhop Label '%'"
- insert line console.log(newValue) after attribute-rows.js:41
- notice that string newValue ends like ".... Webshop Label " leaving out the percentage char and any characters following, consequently any attempt for JSON.parse() fails

-root cause can be found in views/admin/blocks/factfinder_config_field_attributes.tpl:5
[{$availableAttributes|@json_encode}] itself gives valid json but since the fact, that it's enclosed in single quotation like
 available-attributes='[{$availableAttributes|@json_encode}]' it fails immedeately if $availableAttributes contains any quotation mark.

**Comment by a-laurowski** [comment] 2022-02-10 13:26
hi @m-schiewi 
thanks for noticing that. It looks that smarty @json_encode does not properly encode that characters like " and ' and we need to use regular `json_encode` function with additional encoding flags before assigning to a template variable. This will be fixed in next release.

The 4.1.0 is not yet released. Currently is postponed as we are waiting for the WebComponents v4.0.7 to be released before.

**Comment by m-schiewi** [comment] 2022-02-10 15:11
@a-laurowski  I am confused: 4.1.0 is listed at packagist and installed on my side...
![grafik](https://user-images.githubusercontent.com/99345707/153436616-88a831f2-8298-44f9-89ea-670eac3ee248.png)

**Comment by a-laurowski** [comment] 2022-02-11 05:48
hi @m-schiewi  
the problem here is we already pushed the v4.1.0 tag on Wednesday because we were about to release but then, we postpone that, But since tag was already in repository it was automatically loaded by packagist. if you checked the release lists on github you would notice though, that last official release was 4.0.2, and v4.1.0 was not yet officially released.
Sorry for inconvenience. It might be confusing

**Comment by m-schiewi** [comment] 2022-02-11 07:43
thanks a lot!

**Comment by a-laurowski** [comment] 2022-02-11 10:05
@m-schiewi the v4.1.0 is out https://github.com/FACT-Finder-Web-Components/oxid-eshop-module/releases/tag/v4.1.0

**Closed** 2022-03-09 08:12 UTC
